name: Checkout private repository
description: Checks out a private repository using oauth token
inputs:
    token:
        description: OAuth token
        required: true
    repo-url:
        description: GitHub repository url, e.g. https://github.com/<org-or-user>/<repo>.git
        required: true
    ref:
        description: Branch/Tag/Commit reference
        required: true
    path:
        description: Path where to clone the repo. Defaults to $GITHUB_WORKSPACE. If a single name is used, then it will be $GITHUB_WORKSPACE/<name>
runs:
  using: "composite"
  steps:
      - name: Checkout
        shell: bash
        run: |
          https="https://github.com/"
          git="git@github.com:"
          ssh="ssh://git@github.com/"
          https_replace="https://${{ inputs.token }}:x-oauth-basic@github.com/"
          
          url=${{ inputs.repo-url }}
          url=${url/$https/$https_replace}
          url=${url/$git/$https_replace}
          url=${url/$ssh/$https_replace}
          git clone --depth 1 -b ${{ inputs.ref}} $url ${{ inputs.path }}
        
